// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH1qqyyY4RJRG8DS_8h3W_S0CoJb1yw_M',
    appId: '1:976431013374:web:08d257a9b2aa48787974af',
    messagingSenderId: '976431013374',
    projectId: 'sketch-88d9',
    authDomain: 'sketch-88d9.firebaseapp.com',
    storageBucket: 'sketch-88d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlnjeF_2p7U6i5Z3QVUOjq4uZIqjFgOzA',
    appId: '1:976431013374:android:2c87a501660a38787974af',
    messagingSenderId: '976431013374',
    projectId: 'sketch-88d9',
    storageBucket: 'sketch-88d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqTRe-VujX55r6kXYEuAZFxEHef2uOha0',
    appId: '1:976431013374:ios:1ac51691d0f386907974af',
    messagingSenderId: '976431013374',
    projectId: 'sketch-88d9',
    storageBucket: 'sketch-88d9.appspot.com',
    iosClientId: '976431013374-qcg4m949a0njgk7dmv3l67kr3o4a28jm.apps.googleusercontent.com',
    iosBundleId: 'com.L0rentz.sketch',
  );
}
